### ISSUE TITLE
Valid input results in help

### ISSUE THREAD

**Issue by R0flcopt3r** [microsoft/Microsoft-Win32-Content-Prep-Tool#10]
The program lists out the help output when entering a completely valid command with certain executables.

Here I am trying with Adobe Acrobat Reader X:
```
.\IntuneWinAppUtil.exe -c '.\Adober Reader X\' -s '.\Adober Reader X\AcroRdrDC1800920044_nb_NO.exe' -o .
```
Which results in `IntuneWinAppUtil.exe` to output the help section. Some sane error messages would be very helpful, as I have no idea what could be the issue. This also happened with Visma Document Center.

**Comment by nikyusof** [comment]
Hi @R0flcopt3r,

A couple of things:
- Use double quotes.
- The source file shouldn't include the path, just the file name.
- Remove the extra backslash at the end of the source folder input.

So it should be like this:
```
.\IntuneWinAppUtil.exe -c ".\Adober Reader X" -s "AcroRdrDC1800920044_nb_NO.exe" -o .
```
