### ISSUE TITLE
Creating Intune Package

### ISSUE THREAD

**Issue by EMKody137** [microsoft/Microsoft-Win32-Content-Prep-Tool#100]
Hi all, I have been running into an issue today where I am using the prep tool to create an Intune package, however once the command prompt finishes, my destination folder is empty and does not show the package. I am unsure if there is some sort of error, as the command prompt window closes as soon as it finishes running. I tried on two machines, as well as a VM, all running the newest version of Windows 11 Enterprise. I am not sure if it makes a difference, but I am trying to package and distribute the newest version of VS Code. Thanks in advance for any support!

**Comment by sikkepitje** [comment]
You should provide some more info, like what command did you run?
________________________________
Van: Kody Jordan ***@***.***>
Verzonden: Wednesday, May 31, 2023 10:16:04 PM
Aan: microsoft/Microsoft-Win32-Content-Prep-Tool ***@***.***>
CC: Subscribed ***@***.***>
Onderwerp: [microsoft/Microsoft-Win32-Content-Prep-Tool] Creating Intune Package (Issue #100)


Hi all, I have been running into an issue today where I am using the prep tool to create an Intune package, however once the command prompt finishes, my destination folder is empty and does not show the package. I am unsure if there is some sort of error, as the command prompt window closes as soon as it finishes running. I tried on two machines, as well as a VM, all running the newest version of Windows 11 Enterprise. I am not sure if it makes a difference, but I am trying to package and distribute the newest version of VS Code. Thanks in advance for any support!

**Comment by EMKody137** [comment]
I didn't use a command, I just used the prep application and entered in the various folder locations and whether I wanted to add a category folder.

**Comment by miquelcollr** [comment]
> 
Hello! Same issue here using Windows 11 22H2 Enterprise...

**Comment by EMKody137** [comment]
Hi @ianweedlun @miquelcollr,

I'm not sure if you have the capability, but this issue is specific to our version of Win11. Attempting to create the package from a Win10 device seems to work without any issue.

**Comment by ianweedlun** [comment]
Yeah figure I can just spin something up in Hyper-V but would rather not have to lol

**Comment by EMKody137** [comment]
Totally, I wish there was some communication from Microsoft on this...

**Comment by ianweedlun** [comment]
Why would you expect Microsoft to prioritize one of their most important utilities for its cloud MDM running on the latest edition of its newest operating system?!

**Comment by sikkepitje** [comment]
Right now you exactly zero information about your issue. How can you expect anyone to respond to this seriously? What is your command line? What are your parameters? What error message do you get? What is the output? If you are unsure if there is an error, then try harder and make sure there is NO error at all and if there is, post it! 

FYI: I am running Win11 22H2 and i have no issue creating any packages with intunewinapputil at all. So I guess the fault must be at your end. Anyway, no one can tell for sure, as long as you don't provide any detailed information about what you did and what you got.

**Comment by EMKody137** [comment]
Hey @sikkepitje I had written my issue exactly as I had experienced it. As I stated I am unable to get any sort of error code because the command prompt closes immediately. I also answered your question about the command line, but I would be good without your help! Thanks for trying anyway and I am super happy to hear that you aren't experiencing any issues with your deployment!

**Comment by EMKody137** [comment]
Thanks for the useful/productive comment @ianweedlun. I will try this out in the morning!

**Comment by sikkepitje** [comment]
@EMKody137 I am glad to be of help stating the obvious! You can always see any error code , if you stop point-and-clicking command line tools like intunewinapputil.exe. Just open an command window (cmd.exe, pwsh.exe) and work from there. You're welcome. Don't be a cynic. 

@ianweedlun  Now we're getting somewhere. This is or was a known bug. In combination with Windows Terminal. What version of intunewinapputil.exe do you use? run 'intunewinapputil.exe -v' to see the version. Maybe grab the latest version. It should be 1.8.4.

**Comment by ianweedlun** [comment]
Using 1.8.4.

**Comment by ameltzer-MSFT** [comment]
#122
