### ISSUE TITLE
No install instructions

### ISSUE THREAD

**Issue by neschram** [microsoft/Microsoft-Win32-Content-Prep-Tool#105]
Where are the instructions to install? I see the prompts when running the exe but my assumption is that I need to specify the directory and the name of the executable even though I'm running the executable to get the prompt in the first place?

This is usually one of the first things mentioned in a README. There's not even a link to instructions. Just that we need to know there's a privacy policy and terms of use, as if this isn't standard.

**Comment by CakeRepository** [comment]
I'd check this out: https://learn.microsoft.com/en-us/mem/intune/apps/apps-win32-prepare
You don't actually need to install it you just need to run the .exe with the right files in a folder. 
This guide explains how he wraps chocolatey with it and has some pictures: https://www.thelazyadministrator.com/2020/02/05/intune-chocolatey-a-match-made-in-heaven/

If you want to use choco I have these packages too check out my repo(shameless plug) but I got all the info from that and another blog post: https://github.com/CakeRepository/IntunePackages

hope this helps on your journey!
