### ISSUE TITLE
The specified executable is not a valid application for this OS

### ISSUE THREAD

**Issue by tedhenry-lse** [microsoft/Microsoft-Win32-Content-Prep-Tool#107]
![Unsupported 16 bit application](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/145441691/47874102-d09a-45c3-96cd-b78d98643ca4)
![Win10x64](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/145441691/d416fa52-4d84-417e-8ebb-360f4c4915ae)
![Win11x64](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/145441691/279ddae5-53a5-4721-a567-587fa11beff1)

I've tried Win10 Win 11 and running Powershell and Powershell x86 and still cannot get this app to run, please help.

**Comment by DanMarquesPT** [comment]
I have this same error. Any joy on solving this ?

**Comment by tedhenry-dp** [comment]
> I have this same error. Any joy on solving this ?

This version is corrupt, use this one:

https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/archive/refs/tags/1.8.3.zip
