### ISSUE TITLE
Space in folder/file returns in help message

### ISSUE THREAD

**Issue by R0flcopt3r** [microsoft/Microsoft-Win32-Content-Prep-Tool#11]
If the setup folder or setup file has a space in it's name, the program returns the help message. It is not specified this is expected behavior in the documentation, it also doesn't make sense that it should be a problem.

Paths are properly escaped with quotes when this bug occurs.

**Comment by nikyusof** [comment]
Hi @R0flcopt3r,

Would you mind providing an example of command that you tried. I tried running it with a folder and setup file that have spaces in the name and it seems to be working fine.
Here's a sample of my command:

```cmd
C:\temp\Intune> IntuneWinAppUtil.exe -c "C:\temp\Intune\test setup" -s "Test File.msi" -o .\ -q
```

**Comment by R0flcopt3r** [comment]
I no longer work with intune, it's quite possible it's related to issue #10 where I used single quotes. The major problem that I remember is having really bad "error messages", as in, there were none.

**Comment by nikyusof** [comment]
Cool thanks for the feedback. I'll see what I can do to improve the error message.
