### ISSUE TITLE
IntuneWinAppUtil.exe cannot be launched from c# code without console visible

### ISSUE THREAD

**Issue by EdijsPerkums** [microsoft/Microsoft-Win32-Content-Prep-Tool#111]
When launching IntuneWinAppUtil.exe from C# code without console visible we get the following error:
`System.IO.IOException: The handle is invalid.
at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
at Microsoft.Management.Service.IntuneWinAppUtil.LogUtil.PrintProgress(AppContext context)
at Microsoft.Management.Service.IntuneWinAppUtil.PackageUtil.CreatePackage(String folder, String setupFile, String outputFolder, String catalogFolder)
at Microsoft.Management.Service.IntuneWinAppUtil.Program.Main(String[] args)`
It worked fine before #109 

@nikyusof this breaks our apps integration with IntuneWinAppUtil.exe and it would be great if this could be fixed.
Please let me know if more information is required. 
Thank you!

**Comment by rasq** [comment]
Same problem.

**Comment by Hardexit** [comment]
Packaging has also stopped working in [my script](https://github.com/Tealk/Intune-Win32-packaging/blob/master/functions.psm1#L83) since the v1.8.5 update, but back to v1.8.4 it works without any problems.

**Comment by esmorun** [comment]
Same problem here, we use it to package applications from an Azure Devops pipeline. After the 1.8.5 update, it no longer works.

**Comment by MA-Jason-Coombes** [comment]
Issue still occurring.

<img width="566" alt="image" src="https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/143633191/abdefef5-6171-4cd7-a957-f0027f9366dc">

**Comment by jaspain** [comment]
Same issue. IntuneWinAppUtil.exe 1.8.5 must run in a visible window to work properly.

**Comment by jkelly-180** [comment]
Same issue for me when using **RedirectStandardOutput** with **Start-Process** in PowerShell 5.1

**Comment by charchess** [comment]
Same issue for me using intuneWin32App library, really annoying

**Comment by ameltzer-MSFT** [comment]
#89
