### ISSUE TITLE
Unexpected Crashes when Running in Windows Terminal App

### ISSUE THREAD

**Issue by JWohlschlag-Euclid** [microsoft/Microsoft-Win32-Content-Prep-Tool#116]
Multiple versions of the Microsoft Win32 Content Prep Tool crash unexpectedly when running in any shell (Command Prompt, PowerShell, etc.) within the Windows Terminal app. Setting Windows Terminal to open command line applications with Windows Console Host (as per the attached screenshot) and then opening Command Prompt or PowerShell directly so that it does not open inside the Windows Terminal app seems to resolve the issue.

![image](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/114670895/85eb3511-7a40-49f3-89c0-6387619acfe4)

**Comment by TonnyWildeman** [comment]
I caught the accompanying TerminalException using Start-Transcript:
trying to run in Windows.Terminal

> TerminatingError(): "The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while setting the console window title. Contact Microsoft Customer Support Services."
> TerminatingError(Write-Host): "The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services."

> Write-Host: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services.

> Write-Host: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services.
> TerminatingError(out-lineoutput): "The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services."
The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services.

> out-lineoutput: The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services.
> TerminatingError(out-lineoutput): "The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services."
The Win32 internal error "No process is on the other end of the pipe." 0xE9 occurred while getting the console mode. Contact Microsoft Customer Support Services.
