### ISSUE TITLE
v1.8.5 crashing when attempting to package New Teams Bootstrapper

### ISSUE THREAD

**Issue by Petrucci914** [microsoft/Microsoft-Win32-Content-Prep-Tool#118]
Attempting to package this:
[New Teams Bootstrapper](https://learn.microsoft.com/en-us/microsoftteams/new-teams-bulk-install-client#option-1a-download-and-install-new-teams-for-a-single-computer)

It gets close to completing and then crashes.  Happens on, at least, version 1.8.4 and 1.8.5.

Faulting application name: IntuneWinAppUtil.exe, version: 6.2206.38.0, time stamp: 0xa3b9d707
Faulting module name: KERNELBASE.dll, version: 10.0.22621.2792, time stamp: 0x3091b6fb
Exception code: 0xe0434352
Fault offset: 0x000000000006567c
Faulting process id: 0x0x25F4
Faulting application start time: 0x0x1DA39C989D481B5
Faulting application path: E:\intune\IntuneWinAppUtil.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: bbba1ea3-5536-4de1-abbf-df1d23a5a8f4
Faulting package full name: 
Faulting package-relative application ID: 

Fault bucket 1369461804600678810, type 5
Event Name: PowerShell
Response: Not available
Cab Id: 0

Problem signature:
P1: powershell.exe
P2: 10.0.22621.2506
P3: System.ComponentModel.Win32Exception
P4: System.Management.Automation.Host.Host
P5: werShell.ConsoleControl.GetConsoleScreenBufferInfo
P6: werShell.ConsoleControl.GetConsoleScreenBufferInfo
P7: Consol.. main thread
P8: 
P9: 
P10:

**Comment by dancing-groot** [comment]
I'm seeing a similar issue using 1.8.5, even with applications that I have successfully packaged recently.
Faulting application name: IntuneWinAppUtil.exe, version: 6.2312.30.0, time stamp: 0xb443b0f2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.3930, time stamp: 0x9141f979
Exception code: 0xe0434352
Fault offset: 0x000000000002cf19
Faulting process ID: 0x44d8
Faulting application start time: 0x01da5508714c5433
Faulting application path: C:\Users\acop\Repos\Apps\Tools\IntuneWinAppUtil.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report ID: 281e8490-81f9-4efd-8923-fa153e8dfbd0
Faulting package full name: 
Faulting package-relative application ID: 

and

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: IntuneWinAppUtil.exe
P2: 6.2312.30.0
P3: b443b0f2
P4: mscorlib
P5: 4.8.4645.0
P6: 648f6e59
P7: 1695
P8: 198
P9: System.IO.IOException
P10:
