### ISSUE TITLE
Microsoft-Win32-Content-Prep-Tool

### ISSUE THREAD

**Issue by GodsonUkwuoma** [microsoft/Microsoft-Win32-Content-Prep-Tool#119]
When I run the command:.\IntuneWinAppUtil.exe -c "C:\DeployFonts\" -s InstallFonts.ps1 -o C:\output
 the error I keep receiving is Error The folder you specified can not be accessed.
Please specify the source folder??
![image](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/155387880/6a66e9fd-df22-4ced-9ef0-e58925932696)

**Comment by diecknet** [comment]
It looks like you ran the program by double-clicking it. Try running your command in a new Terminal windows (cmd.exe).
