### ISSUE TITLE
Can I get 64bit version?

### ISSUE THREAD

**Issue by cerveos24** [microsoft/Microsoft-Win32-Content-Prep-Tool#12]
I get the following error: IntuneWinAppUtil.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

**Comment by nikyusof** [comment]
Hi @cerveos24, are you still having this problem using the latest version of the tool? If yes, would you mind providing me some more information about your system and the actual error message that you are getting. Thank you.

**Comment by ryandengstrom** [comment]
I am seeing the issue on 20H2 with v1.8.2 of the tool.
![Screenshot 2021-02-18 104922](https://user-images.githubusercontent.com/56974789/108391109-fb6b8600-71d6-11eb-9cf5-4b2b8cc5de1e.png)

**Comment by justinbdavis** [comment]
I'm having the exact same issue. Has there been any resolve for this?

**Comment by jeff-simeon** [comment]
In case you're open to an alternative, http://github.com/simeoncloud/IntuneAppBuilder/ has the same functionality as this tool (plus the ability to publish apps) and does not suffer from this limitation.

Full disclosure - I work at Simeon.
