### ISSUE TITLE
Why is this tool not open-sourced?

### ISSUE THREAD

**Issue by camptatopenmars** [microsoft/Microsoft-Win32-Content-Prep-Tool#120]
It is now 2024.... Microsoft generally has figured out that open-source benefits adopting of Microsoft platform technologies - such as Intune in this instance....

The tool does not really work at all currently _except_ if you directly run it elevated and spoon feed it parameters.  It just crashes otherwise and unhelpfully closes my terminal so I can't even see the error text it might have been outputting.  Which is _an_ issue.  But what would actually be _helpful_ is an open-source tool that I could fix and adapt as I need to automate my workflow.

**Comment by have-no-clue-what-im-doing** [comment]
Yeah, that ain't ever happening.... :/

**Comment by michaelmsonne** [comment]
Yes I say the same over the year.. :(

There is so many bugs to and it´s hard to fix them..

And the v. of the .exe itself is even not the samt as the releases here on GitHub..

![image](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/assets/49366751/82da94cc-cd8e-4922-b6b8-fa7063245d37)

**Comment by ameltzer-MSFT** [comment]
#75
