### ISSUE TITLE
IntuneWinAppUtil crashing in Terminal when using Windows Terminal host

### ISSUE THREAD

**Issue by sean-mullen** [microsoft/Microsoft-Win32-Content-Prep-Tool#122]
A windows update broke this utility months ago.

Fix it please.

**Comment by cu-ri-os-i-ty** [comment]
It worked for me instead of launching it in PowerShell or Terminal..  Double-clicked on the launcher, and it went into its own window. I typed in the required folder, the .exe, and the output, and it worked. 

Give it a go and let me know. 

GL

**Comment by thomasjsweet** [comment]
This whole thing is "hit or miss" for me. It may work once, then fails 10 times in a row, often failing 61%. I had to complete one and opened the app by double clicking at it worked this time.  Thx @cu-ri-os-i-ty. I will keep an eye on it as I need to do more over the next few weeks.

**Comment by Voljka1** [comment]
Windows 11 Pro, 23H2, build 26040.1000.
IntuneWinAppUtil.exe -v 1.8.5.0

Crashed at 62% in Terminal, cmd.exe, when running from .bat file or just in command line:
C:\work\INTUNE\IntuneWinAppUtil.exe -c "C:\work\INTUNE\Notepad++ 8.6.1" -s "npp.8.6.1.Installer.x64.exe" -o "C:\work\INTUNE\Output"

Does not crash, if window are maximized. Just AMAZING. Wow...

**Comment by IHash223** [comment]
@Voljka1 is right (at least for me).

If I run in cmd.exe, powershell.exe, pwsh.exe or double-clicked, it crashed, unless the windows are maximised.

**Comment by MarcLaf** [comment]
Just had to update a package now and noticed this happening.

**Comment by Sinderan** [comment]
> @Voljka1 is right (at least for me).
> 
> If I run in cmd.exe, powershell.exe, pwsh.exe or double-clicked, it crashed, unless the windows are maximised.

Wow, I've been fighting with this, and as soon as I maximized the terminal it ran perfectly.

**Comment by TassieTrooper** [comment]
Crashing for me also Seems to be at the encrypting stage

**Comment by tld6764** [comment]
Double-clicking on the IntuneWinAppUtil.exe file is the only thing that works for me.

**Comment by uecasm** [comment]
See #116 and microsoft/terminal#16432; it seems to be an incompatibility with Windows Terminal.  I haven't had any issues after switching it back to the Console Host.

**Comment by TassieTrooper** [comment]
MSFT still need to fix it, after all, Terminal is their (MSFTs) app and the Windows 11 >23H1 default console at that.
________________________________

**Comment by markdall** [comment]
@nikyusof @stevgao Are you all okay? This tool has been crashing in Windows Terminal since last November. Any kind of response to all these Issues would be appreciated so it stops looking like abandonware. <3 (and I hope neither of you were laid off!)

**Comment by nikyusof** [comment]
Hello everyone,
I will be taking a look at this in the coming week and will update the tool with the fixes.

**Comment by markdall** [comment]
Thanks and sorry to bother you!

**Comment by nikyusof** [comment]
Hi everyone,
Would you mind trying out the new release and see if that fixes the issue?
Please and thank you!

**Comment by Voljka1** [comment]
> Hi everyone, Would you mind trying out the new release and see if that fixes the issue? Please and thank you!

App works in not maximized terminal window. But if I resize terminal window while app working, it crashed.

**Comment by nikyusof** [comment]
@Voljka1 thank you for the feedback.
Let me take a look at that.

**Comment by tylermontneyacc** [comment]
Issue persists in 1.8.6. If run through Terminal, crashes around 60%. If run in CMD, works fine. My guess is around 60% the content forces the output to scroll, and that functionality changed between CMD and Terminal. OpenConsole.exe has exception code 0xc0000094, which I believe translates to "divide by zero".

**Comment by nikyusof** [comment]
Thanks @tylermontneyacc . I am planning to push out another minor fix soon and hopefully fixes this issue.
I would appreciate it if you retest once it is out.

**Comment by ianweedlun** [comment]
Does the fact that all of the older issues that were closed as duplicates of this issue mean we might see a fix for this soon?

**Comment by MarcLaf** [comment]
@ianweedlun 
> Does the fact that all of the older issues that were closed as duplicates of this issue mean we might see a fix for this soon?

I just downloaded the latest available version today and it worked with no issues (and no prior workarounds). Not sure if I got lucky or it is indeed fixed.

**Comment by ameltzer-MSFT** [comment]
There's been several fixes aroud this issue in the latest build. I was unable to repro with the latest build even when using the native Terminal (vs conhost). If you're still seeing this occur in the latest release, please let us know.
