### ISSUE TITLE
Unzip fails if double-byte characters exist in the content file name.

### ISSUE THREAD

**Issue by hogawaMS** [microsoft/Microsoft-Win32-Content-Prep-Tool#13]
For example, processing such as copying a file containing double byte in batch file to the desktop causes an error.

As a temporary correspondence, after copying a single-byte file, it is avoided by the process of renaming to double-byte in consideration of usability, but I would like double-byte correspondence as well.

**Comment by sebastianwrtlprmpft** [comment]
Same here. We have a package that contains double-byte file names. Renaming them before creating the intunewin file and naming them back at deployment time is not a desirable way :-)
Thank you in advance & best regards!

**Comment by okieselbach** [comment]
Add support for Unicode file and folder name
https://github.com/Microsoft/Microsoft-Win32-Content-Prep-Tool/releases/tag/v1.7

this should fix the problem... 👍
