### ISSUE TITLE
Quiet parameter does nothing

### ISSUE THREAD

**Issue by v-tbert** [microsoft/Microsoft-Win32-Content-Prep-Tool#15]
Running with the -q option doesn't make any discernible difference in the amount of output. I still see about 20 lines of output indicating all the intermediary steps being performed.

**Comment by nikyusof** [comment]
Hi @v-tbert ,

As mentioned in the README:
```
If -q is specified, it will be in quiet mode. If the output file already exists, it will be overwritten.
```

In other words, the `-q` param is being used for the output file and not the output message.
