### ISSUE TITLE
Packages are to big

### ISSUE THREAD

**Issue by nebi52** [microsoft/Microsoft-Win32-Content-Prep-Tool#21]
Hello, why why the packages always so much lurcher after converting the .exe into a .intunewin file?
For example. I downloaded Adobe Acrobat Reader DC with 180MB. After the script the .intunewin file is 600MB large. 
Am I doing something wrong or is it just like that?

**Comment by tansson** [comment]
@nebi52, you have to place the setup file in an empty folder as the wrapper packages all of the files within the same folder of the specified setup file.

**Comment by nikyusof** [comment]
Hi @nebi52,

Here's a sample of folder structure and command to run:

```
Folder structure:
C:
├── temp
│   └── adobe
│         └── adobe.exe

C:\temp> IntuneWinAppUtil.exe -c .\adobe -s adobe.exe -o .\ -q
```
