### ISSUE TITLE
problems with preping a folder structure

### ISSUE THREAD

**Issue by RLE81** [microsoft/Microsoft-Win32-Content-Prep-Tool#23]
I'm trying to add some Autodesk products in intune.

Unfortunately I come across an issue that certain subfolders are not wrapped.
Is there a limit on the number of subfolders or is there a limit on the file length

example
Img \ x64 \ FormIt \ ce1643 \ 3a0191

**Comment by nikyusof** [comment]
@RLE81, are you still having this issue with the latest version of the tool? I believe there are not limit on the number of subfolders or the file length.
