### ISSUE TITLE
Executing tool multiple times causes strange behaviour

### ISSUE THREAD

**Issue by anberger** [microsoft/Microsoft-Win32-Content-Prep-Tool#24]
I have a problem with the provided tool. Everytime I try to package the executable the filesize increases. I perform always the same commands. Is there somewhere a cache I can cleanup?

![image](https://user-images.githubusercontent.com/8898749/71371042-22690080-25b0-11ea-81ac-1886a88cddd0.png)

**Comment by the-sw** [comment]
The destination folder you have set is the same as the source, so it'll be packaging your other .intunewin files inside the new intunewin it creates

**Comment by nikyusof** [comment]
Thanks for the response @the-sw!
@anberger please look at the response above for your issue.
