### ISSUE TITLE
"Entries larger than 4GB are not supported in update mode"

### ISSUE THREAD

**Issue by 1994Nicklas** [microsoft/Microsoft-Win32-Content-Prep-Tool#25]
Files that are bigger then 4GB can't be packages with the tool in version 1.6, we keep getting the error "Entries larger than 4GB are not supported in update mode". It seems to be working when using the version 1.5 
<img width="637" alt="ver1 6" src="https://user-images.githubusercontent.com/60114578/72755463-d8813380-3bca-11ea-81ed-3f3c0684ae7a.png">

**Comment by nikyusof** [comment]
@1994Nicklas please try the latest release. I just tried packaging a file greater than 4GB and it seems to be working fine.
