### ISSUE TITLE
win32 extract product version intune

### ISSUE THREAD

**Issue by alventech** [microsoft/Microsoft-Win32-Content-Prep-Tool#27]
is it not supported to extract product version from win32 to MEM - Intune? Have uploaded win32 using both manual & Graph API. However, I cannot use the Version to work.  

![Productversion](https://user-images.githubusercontent.com/49759214/74430984-4c2aff00-4e5e-11ea-9068-8840217304f5.png)

**Comment by Skymanden** [comment]
Hi
Not at the moment.
If you use LOB app (.msi) you extract more info abount the package.
![image](https://user-images.githubusercontent.com/60913871/74512744-3f171a00-4f09-11ea-80e1-9386c517d053.png)


**.intunewin format**: 
![image](https://user-images.githubusercontent.com/60913871/74512772-4a6a4580-4f09-11ea-830d-def334f6d47a.png)

**Comment by nikyusof** [comment]
@alventech `msi`'s will have the version whereas `exe`'s don't. here's an image of a Win32 app that is created from an `msi`.

![image](https://user-images.githubusercontent.com/64165110/101123971-dc336400-35aa-11eb-9c27-58a9b682371a.png)
![image](https://user-images.githubusercontent.com/64165110/101124039-07b64e80-35ab-11eb-9857-6328b0edf49a.png)
