### ISSUE TITLE
Why can't we get the source code?

### ISSUE THREAD

**Issue by okieselbach** [microsoft/Microsoft-Win32-Content-Prep-Tool#28]
What is the reason behind of not publishing the source code of this fairly small tool?
There are issues open since a very long time and it seems nobody cares about them. Why can't the community support the further development of the tool. Let the community do some pull requests to help fix issues. Like the wrong character set handling in filenames etc.

**Comment by admin-simeon** [comment]
@okieselbach 
We’ve decided to open source the Intune application packaging and publishing component of our Micrsoft 365 Management Suite which has the same functionality as this tool. You can find the repository here: https://github.com/simeoncloud/IntuneAppBuilder

**Comment by jozefizso** [comment]
Hi @stevgao, it is possible to open source this tool?

**Comment by Joly0** [comment]
@nikyusof Is it possible to get the source code somehow?

**Comment by camptatopenmars** [comment]
just lol.  won't fix won't fixing the tool.

**Comment by jozefizso** [comment]
@ameltzer-MSFT what's the point of this repository and the tool in it? There's no communication from Microsoft team about this, no communication with the OSS community.
