### ISSUE TITLE
I am using this tool to create an executable for sophos endpoint 

### ISSUE THREAD

**Issue by griedel** [microsoft/Microsoft-Win32-Content-Prep-Tool#3]
when this is ran it creates a file called "INTUNEWIN file" how the heck do I turn this into a .exe from here. this doesn't work like the old tool did.

**Comment by nitvit610** [comment]
The .Intunewin file is uploaded to Intune and then deployed to machine through that. 
It is just a packaged version of the .exe you used the tool on.

**Comment by nikyusof** [comment]
Hi @griedel,
Just like @nitvit610 mentioned, using this tool will generate an `.intunewin` file which is being used to upload to Intune.
