### ISSUE TITLE
1.7 fails to run on windows core: reqs missing or bug?

### ISSUE THREAD

**Issue by msfreaks** [microsoft/Microsoft-Win32-Content-Prep-Tool#35]
1.7 fails to run:
![image](https://user-images.githubusercontent.com/17710654/78972070-3ad43b00-7b0d-11ea-92df-4f2a740e02d3.png)

older version runs fine.

Please:
1. provide a version that does run on servercore:latest, or
2. provide a list of requirements to make it run on servercore:latest

**Comment by msfreaks** [comment]
On second thought: I think there's now an OS limitation in the .exe?
It's not just servercore but server as well:
![image](https://user-images.githubusercontent.com/17710654/78972323-c64dcc00-7b0d-11ea-8e8a-0f3538c7d1d7.png)

**Comment by admin-simeon** [comment]
@msfreaks
We’ve decided to open source the Intune application packaging and publishing component of our Microsoft 365 Management Suite which has the same functionality as this tool. You can find the repository here: https://github.com/simeoncloud/IntuneAppBuilder. It is written for dotnet core (3.1) and should be compatible with Windows Server Core

**Comment by msfreaks** [comment]
Thank you! I will look into this. Just to be clear, this is not a Microsoft tool, but of your own making?

**Comment by admin-simeon** [comment]
@msfreaks That is correct
