### ISSUE TITLE
[v1.7] Unable to upload packaged Win32 classic apps

### ISSUE THREAD

**Issue by infraweavers** [microsoft/Microsoft-Win32-Content-Prep-Tool#36]
For example, wireshark packaged with v1.7:
![image](https://user-images.githubusercontent.com/36475663/79768288-7bf4f800-8322-11ea-87f1-eeeeb2f6afed.png)
and with v1.6:
![image](https://user-images.githubusercontent.com/36475663/79768669-0178a800-8323-11ea-8dc9-175ca419a406.png)

This is under Windows 10 1909 (18363.720)

    $PSVersionTable.PSVersion
    
    Major  Minor  Build  Revision
    -----  -----  -----  --------
    5      1      18362  628

And .NET Framework 4.8.03752:

    gci 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full\'
    
    
        Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full
    
    
    Name                           Property
    ----                           --------
    1033                           CBS           : 1
                                   Install       : 1
                                   Release       : 528040
                                   Servicing     : 0
                                   TargetVersion : 4.0.0
                                   Version       : 4.8.03752

Happy to provide further information by request.
Thank you.

**Comment by salihzett** [comment]
+1

**Comment by salihzett** [comment]
same issue also with v.1.8.1

**Comment by Jonny2026** [comment]
+1

**Comment by admin-simeon** [comment]
@Jonny2026  @salihzett @infraweavers 
We’ve decided to open source the Intune application packaging and publishing component of our Microsoft 365 Management Suite which has the same functionality as this tool. You can find the repository here: https://github.com/simeoncloud/IntuneAppBuilder. I can vouch that the functionality works both programmatically and for uploading via the portal.

**Comment by treborb123** [comment]
I'm having the same problem as the others. Also happening using IntuneAppBuilder. 
I can run the program I'm trying to package up as an Intunewin file just fine on the desktop so I don't think there's anything wrong with what I'm trying to package up.

**Comment by stefnash** [comment]
Same issue as original poster with both v1.7 and v1.8.1

**Comment by slowbiz** [comment]
Also having same issue.

**Comment by admin-simeon** [comment]
> I'm having the same problem as the others. Also happening using IntuneAppBuilder.
> I can run the program I'm trying to package up as an Intunewin file just fine on the desktop so I don't think there's anything wrong with what I'm trying to package up.

Hey there. Please note that the IntuneAppBuilder spits out two intunewin files - one for the portal and one for the api. When trying with the portal, did you use the portal.intunewin file? I just tried and it worked for me. 

You can also use the IntuneAppBuilder publish command to bypass the portal altogether.
