### ISSUE TITLE
New Build 1.8 will not run

### ISSUE THREAD

**Issue by TRGibson** [microsoft/Microsoft-Win32-Content-Prep-Tool#38]
Just trying to display the help returns the following:
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'IntuneWinAppUtil, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A) ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
   --- End of inner exception stack trace ---

**Comment by nikyusof** [comment]
@TRGibson please use the latest release [v1.8.1](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/releases/tag/v1.8.1). Thanks!
