### ISSUE TITLE
can't determine release version of file

### ISSUE THREAD

**Issue by sikkepitje** [microsoft/Microsoft-Win32-Content-Prep-Tool#43]
I have trouble determining the version of the executable I downloaded earlier. 

Inspecting the properties of IntuneWinAppUtil.exe v1.8.1 gives me the following  information:
File version: 6.2006.10.0
Product version : 6.2006.10.0 d0d1b925 Intune-Svc=EMSAgent.develop (AzBuildSC-Ma05.200424-1034)

I can't say for certain that this file is the latest release v1.8.1 by looking at the properties alone. It would be nice to show the release version on the command line , like using -h parameter

**Comment by SteveBurkettNZ** [comment]
Came here to say the same thing. Was expecting the version number to be shown in the usage (-h) output but no.
