### ISSUE TITLE
Unable to run on Windows 10 19042.685 64 bit. 

### ISSUE THREAD

**Issue by jamesguyz** [microsoft/Microsoft-Win32-Content-Prep-Tool#47]
I am unable to run this application on Windows 10 19042.685 64 bit. 
###########################################################
From PowerShell windows: 
Program 'IntuneWinAppUtil.exe' failed to run: The specified executable is not a valid application for this OS platform. At line:1
char:1
+ .\IntuneWinAppUtil.exe
+ ~~~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ .\IntuneWinAppUtil.exe
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
###########################################################
From CMD: 
Unsupported 16-Bit Application
The program or feature "\??\C:\temp\Packager\IntuneWinAppUtil.exe" cannot stat or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask it a 64-bit Windows compatible version is available.  
###########################################################
I have change the Compatibility Mode that is runs in as part of troubleshooting but still have not ran successfully. 
###########################################################
Windows Event Log:
Log Name:      Application
Source:        Wow64 Emulation Layer
Date:          1/8/2021 2:24:43 PM
Event ID:      1109
Task Category: None
Level:         Information
Keywords:      Classic
User:          N/A
Computer:      XXXXXXXXXXX
Description:
The program or feature "\??\C:\temp\Packager\IntuneWinAppUtil.exe" cannot start or run due to incompatibity with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Wow64 Emulation Layer" />
    <EventID Qualifiers="16384">1109</EventID>
    <Version>0</Version>
    <Level>4</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2021-01-08T21:24:43.5810744Z" />
    <EventRecordID>55828</EventRecordID>
    <Correlation />
    <Execution ProcessID="0" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>XXXXXXXX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>\??\C:\temp\Packager\IntuneWinAppUtil.exe</Data>
  </EventData>
</Event>
###########################################################

**Comment by jamesguyz** [comment]
Interesting:
I have downloaded IntuneWinAppUtil.exe to three different PCs and thy are all coming up as 108 KB. 
I had one of my coworkers in India test this and they downloaded it and it was only 52.3 KB and ran without an issue.  
I had him email the file and it is working for me as well.

**Comment by dgunner-glitch** [comment]
I had the same issue - cloning seemed to solve it rather than downloading the exe

**Comment by alexknelson** [comment]
I'm seeing the same issue.

**Comment by cuatrix-bensonlee** [comment]
I have exactly the same issue on 1.8.2 even from outside the US.  This is what I noticed though:  the problematic "exe" (more than 100kb in size) is not really an exe file even if it is downloaded as an exe file.  The file can be opened directly from notepad, and you would see that it is actually an html file.  You can actually rename it back to .html and open it with your browser where you will see a download link to the actual exe file (which also does not work).

The correct file, which is a real exe file, is roughly around 53KB in size.  Version 1.8.2 has an MD5 hash of E8C14D09B6FAA76B3850FC0CBA41D78B.

Best is to simply clone the repo and extract the exe in the zip file.

**Comment by o-l-a-v** [comment]
As I wrote here:

https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/issues/61#issuecomment-991047859

Just downlaod the sources ZIP from releases. SHA256 from working 1.8.3 on Windows 11 22000.348:

* 83dab0354422525eb0e73fe3b9395efb34426a6cc68ef8670722939593cb7120
