### ISSUE TITLE
Some help needed

### ISSUE THREAD

**Issue by frmo033** [microsoft/Microsoft-Win32-Content-Prep-Tool#48]
I have 1 EXE and 1 CFG file that I want to get togehter in an INTUNEWIN file. I use IntuneWinAppUtil. As source I point to my EXE file. For catalog I point to the sourcefolder where bothe EXE and CFG are in. That generates an error the temp file intunepackage.intunewin allready exists.

Am I doing something wrong?

Using the version 1.8.2

**Comment by sikkepitje** [comment]
Yes. Don't use the catalog folder option.
Let "source folder" point to the folder with both the EXE and the CFG file
, using -c .
Point "source setup file" to just the base name of the EXE file, using -s .
that should do it.



Op do 21 jan. 2021 om 15:56 schreef frmo033 <notifications@github.com>:

**Comment by frmo033** [comment]
Thanks for your reply.
Is there a way/tool to check what’s realy in the INTUNEWIN file (like you can also view the content of a MSI file with an MSI viewer)?

Van: Paul Wiegmans <notifications@github.com>
Verzonden: donderdag 21 januari 2021 17:19
Aan: microsoft/Microsoft-Win32-Content-Prep-Tool <Microsoft-Win32-Content-Prep-Tool@noreply.github.com>
CC: Frederik Moquette <frederik.moquette@unexus.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/Microsoft-Win32-Content-Prep-Tool] Some help needed (#48)

Yes. Don't use the catalog folder option.
Let "source folder" point to the folder with both the EXE and the CFG file
, using -c .
Point "source setup file" to just the base name of the EXE file, using -s .
that should do it.



Op do 21 jan. 2021 om 15:56 schreef frmo033 <notifications@github.com<mailto:notifications@github.com>>:

**Comment by sikkepitje** [comment]
I don't know of a way to decompile/decrypt an intune win file, but maybe Google knows better. It's just what you put in there.

________________________________
Van: frmo033 <notifications@github.com>
Verzonden: Friday, January 22, 2021 10:11:03 AM
Aan: microsoft/Microsoft-Win32-Content-Prep-Tool <Microsoft-Win32-Content-Prep-Tool@noreply.github.com>
CC: Paul Wiegmans <sikkepitje@gmail.com>; Comment <comment@noreply.github.com>
Onderwerp: Re: [microsoft/Microsoft-Win32-Content-Prep-Tool] Some help needed (#48)


Thanks for your reply.
Is there a way/tool to check what’s realy in the INTUNEWIN file (like you can also view the content of a MSI file with an MSI viewer)?

Van: Paul Wiegmans <notifications@github.com>
Verzonden: donderdag 21 januari 2021 17:19
Aan: microsoft/Microsoft-Win32-Content-Prep-Tool <Microsoft-Win32-Content-Prep-Tool@noreply.github.com>
CC: Frederik Moquette <frederik.moquette@unexus.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/Microsoft-Win32-Content-Prep-Tool] Some help needed (#48)

Yes. Don't use the catalog folder option.
Let "source folder" point to the folder with both the EXE and the CFG file
, using -c .
Point "source setup file" to just the base name of the EXE file, using -s .
that should do it.



Op do 21 jan. 2021 om 15:56 schreef frmo033 <notifications@github.com<mailto:notifications@github.com>>:

**Comment by frmo033** [comment]
Hi,

Maybe I don’t understand it fully. This is what I do:

I have a folder myApp containing myApp.exe and myApp.exe.cfg.
I need both exe and cfg to become part of the .intunewin file.

Not working: C:\IntuneWinAppUtil_Test\IntuneWinAppUtil.exe -c C:\IntuneWinAppUtil_Test\myApp -s myApp -o C:\IntuneWinAppUtil_Test
Works: C:\IntuneWinAppUtil_Test\IntuneWinAppUtil.exe -c C:\IntuneWinAppUtil_Test\myApp -s myApp.exe -o C:\IntuneWinAppUtil_Test

What I need to know, is when it works the .cfg file included in the package or not?

Van: Paul Wiegmans <notifications@github.com>
Verzonden: donderdag 21 januari 2021 17:19
Aan: microsoft/Microsoft-Win32-Content-Prep-Tool <Microsoft-Win32-Content-Prep-Tool@noreply.github.com>
CC: Frederik Moquette <frederik.moquette@unexus.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [microsoft/Microsoft-Win32-Content-Prep-Tool] Some help needed (#48)

Yes. Don't use the catalog folder option.
Let "source folder" point to the folder with both the EXE and the CFG file
, using -c .
Point "source setup file" to just the base name of the EXE file, using -s .
that should do it.



Op do 21 jan. 2021 om 15:56 schreef frmo033 <notifications@github.com<mailto:notifications@github.com>>:

**Comment by svdbusse** [comment]
Yes everything that was in the directory specified will be included in the .Intunewin file.
