### ISSUE TITLE
 System.IO.IOException: Stream was too long. 

### ISSUE THREAD

**Issue by Robsi01** [microsoft/Microsoft-Win32-Content-Prep-Tool#58]
I am trying to package up some .exe files that total 5.18GB 

It seems that even though this is below the 8GB limit set by MS, the tool is not able to handle such large files. 

![image](https://user-images.githubusercontent.com/28739855/123695767-df49b680-d852-11eb-93b6-10edfe523442.png)

**Comment by Avi1689** [comment]
Hello Team,
Good Day!

I have the same issue. It would be of great help, if someone has a solution for this.
@Robsi01 - were you able to fix this?

Regards,
Avi

**Comment by Robsi01** [comment]
@Avi1689 nope, not fixed. I feel its a 32bit limitation, but I'm not sure. Tried lots to get it to work. No success.
If you find a way please say :)

Thanks Rob

**Comment by Avi1689** [comment]
@Robsi01 Sure, I will :)

**Comment by Avi1689** [comment]
Hello @Robsi01 - I used the old prep tool from Oct 2020 and it never gave me this error! I have attached one here, please give it a try and share the results.
[WindowsIntunePrepTool.zip](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/files/6777395/WindowsIntunePrepTool.zip)

**Comment by admin-simeon** [comment]
The open source Simeon IntuneAppBuilder (https://github.com/simeoncloud/IntuneAppBuilder) does not suffer from this limitation. (Full disclosure, I work at Simeon).

**Comment by XxQuaDxX** [comment]
I am having this issue too. Using the old version of the tool posted by @Avi1689 does work, but please fix this in the current version!!

**Comment by jonconwayuk** [comment]
I also have the same issue here.

**Comment by hellojoe88** [comment]
I have the same issue. Is there a workaround for this? I cannot pack a 2.54GB file because of the same issue

**Comment by DanMorrie1** [comment]
Hi guys, i took a look into this because I had the same issue and found that the tool is compressing everything in the source folder you specify.

So, you may only be converting the 1 exe or msi file, the tool is still compressing everything else that sits in the same folder.
That means, if your source folder is your downloads folder, it will be compressing everything in the downloads folder along with your file and then either runs out of memory or creates a massive .intunewin file

Let me know if this helps anyone

**Comment by gezakukoda** [comment]
I have the same issue with the Slack per user installer:
https://slack.com/help/articles/212475728-Deploy-Slack-via-Microsoft-Installer

**Comment by gezakukoda** [comment]
> Hi guys, i took a look into this because I had the same issue and found that the tool is compressing everything in the source folder you specify.
> 
> So, you may only be converting the 1 exe or msi file, the tool is still compressing everything else that sits in the same folder. That means, if your source folder is your downloads folder, it will be compressing everything in the downloads folder along with your file and then either runs out of memory or creates a massive .intunewin file
> 
> My recommendation would then be to create a subfolder that only has the exe or msi file you wish to convert in it and run the tool across that file.
> 
> Let me know if this helps anyone

I have just seen your comment after I have posted. With empty folder the packaging was successful.

**Comment by ConfigMangler** [comment]
Not sure that helps? Fair enough for a MSI but not for an Office app such as Project.

**Comment by ConfigMangler** [comment]
Yes old one working. Thanks Avi1689. old one 15mb ram used. New one 4 Gb and crash. 
Guess Microsoft testing was point 1.8.3 at notepad.exe. It works! Job done.

**Comment by JLambEJG** [comment]
Same issue here. Version 1.8.3 produces the error. Thanks to @Avi1689 for providing an older version. I can't tell what version it is, but it works.

**Comment by gvijaykumar20** [comment]
Hey everyone, 
This issue is now fixed with the latest release ([v1.8.4](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/pull/70)).

**Comment by XxQuaDxX** [comment]
> Hey everyone, This issue is now fixed with the latest release ([v1.8.4](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/pull/70)).

Thank you so much!!!!!

**Comment by AldoSan666** [comment]
> Hi guys, i took a look into this because I had the same issue and found that the tool is compressing everything in the source folder you specify.
> 
> So, you may only be converting the 1 exe or msi file, the tool is still compressing everything else that sits in the same folder. That means, if your source folder is your downloads folder, it will be compressing everything in the downloads folder along with your file and then either runs out of memory or creates a massive .intunewin file
> 
> My recommendation would then be to create a subfolder that only has the exe or msi file you wish to convert in it and run the tool across that file.
> 
> Let me know if this helps anyone

-----------------This Worked perfectly, I just created an empty new folder, and dragged the installer into it!

Thanks alot!
