### ISSUE TITLE
.MSI source management

### ISSUE THREAD

**Issue by akukalle** [microsoft/Microsoft-Win32-Content-Prep-Tool#6]
.MSI might need access to original installation media during Repair/Update/Uninstall. Location of media is stored to registry HKEY_CLASSES_ROOT\Installer\Products\"package"\SourceList. This information is written based location where MSI is stored during installation. 
Intune extracts Intunewin file to c:\windows\IMECache -> Installs MSI -> Deletes media. After this sourcelist in registry points location what doesn't exists. This can end up in scenario where packages repair/update/uninstall might fail.
My workaround is copy installation media to client and add it's location to registry. Is it possible build this or something else functionality to intunewin to fix this issue?

**Comment by allexb** [comment]
absolutely agree with you. Self healing will also fail in this case.
This is not only related to intunewin but to msi as well.

**Comment by akukalle** [comment]
> absolutely agree with you. Self healing will also fail in this case.
> This is not only related to intunewin but to msi as well.

Totally forgot self healing. Actually this is very big problem if you use self healing to install files to user profile. Other deployment solutions has workaround to this. For example SCCM is able to download media from DP if local cache is deleted(basically they just write DP information to registry).

**Comment by allexb** [comment]
Usually we use copying of MSI to place where it will not be deleted. For Example Program Files\MSOCache\...
And then install MSI from this place.
