### ISSUE TITLE
IntuneWinAppUtil.exe on Win 11 (10.0.22000.120): "the app cannot be started"

### ISSUE THREAD

**Issue by andy-connective** [microsoft/Microsoft-Win32-Content-Prep-Tool#61]
It appears there is an issue with detecting .Net - the error message is:

![image](https://user-images.githubusercontent.com/85059997/128772928-a0f6e32d-d902-4f13-b925-76626900db84.png)

Yes takes you to: 

https://docs.microsoft.com/en-gb/dotnet/framework/install/application-not-started?version=(null)&processName=IntuneWinAppUtil.exe&platform=0009&osver=6&isServer=0&shimver=4.0.30319.0

Running the advised tool simply advises: ".NET Framework 4.8 or a later update is already installed on this computer."

This is on the latest build of Windows 11 (Insider Beta Channel, see details below) and a recent .Net quality update (also see below) has been applied. I've tried installing .Net 4.8 which confirms it is already installed and therefore won't install.

Cumulative Update for Windows 11 (10.0.22000.120) (KB5005188)
2021-07 Cumulative Update for .NET Framework 3.5 and 4.8 for Windows 11 for x64 (KB5004316)

Also reporting to Windows 11 team of course.

**Comment by o-l-a-v** [comment]
I tried right click -> Save from the files view, it would not run on my machine either.

* https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/blob/master/IntuneWinAppUtil.exe
  * Like righ click and save this one ^.

Then I tried downloading the "Source code (zip)" from the release, it worked.

* https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/archive/refs/tags/1.8.3.zip

Running 22000.448.

**Comment by KennethValentin** [comment]
I have the same issue as @o-l-a-v  I am not able to run the .exe file on 64 bit machine. I have tried to change the settings in IIS to allow the machine to run 32 bit applications, but still it will not work.
