### ISSUE TITLE
Generating huge files

### ISSUE THREAD

**Issue by leosiqueira10** [microsoft/Microsoft-Win32-Content-Prep-Tool#62]
Hello!
I'm using the current version (1.8.3.0) and **sometimes** I get a huge intunewin file. I managed to create some intunewin with almost the same size (1Mb less in my last convertion) but now I'm packing Microsoft Visual C++ 2017 Redistributable, where the source exe is ~24Mb and the intunewin is 1,1Gb!
The same happened for .NET Framework 4.8: 118Mb turned into a 1,1Gb file.
Rebooted, downloaded the prep tool again, still same result.

Anyone with the same issue?

Thanks!

**Comment by Xtraim** [comment]
Hi,
Did you package the app in an empty folder with only the soft ?
When the tool is packaging, it takes all of the folder content.
So to explain, if you download visual.exe in  “c:\users\you\downloads”
and you choose this “downloads” folder as source folder, even if you point at the soft “visual.exe” at the second command (where it asks name of the soft).
It will package the whole “downloads” folder including visual.exe + all of your previously downloaded files.
Right click on the downloads folder to have size of the folder you should find the same size (minus the intunewin package if “downloads” is also your destination.

To do it correctly, an exemple:

create a folder with the package name in your downloads (ex: fullpath\downloads\visual)
-> Put what you need inside “visual” folder
—> point this folder in source
-> point the soft (ex: visual.exe)
-> give a destination path for your intunewin package (ex: fullpath\downloads\packages)
I’m writing from my phone in subway so sorry for errors.




Le 21 sept. 2021 à 19:40, leosiqueira10 ***@***.***> a écrit :

﻿

Hello!
I'm using the current version (1.8.3.0) and sometimes I get a huge intunewin file. I managed to create some intunewin with almost the same size (1Mb less in my last convertion) but now I'm packing Microsoft Visual C++ 2017 Redistributable, where the source exe is ~24Mb and the intunewin is 1,1Gb!
The same happened for .NET Framework 4.8: 118Mb turned into a 1,1Gb file.
Rebooted, downloaded the prep tool again, still same result.

Anyone with the same issue?

Thanks!

**Comment by leosiqueira10** [comment]
Hi Xtraim
Yep, that was the issue, thanks very much!
