### ISSUE TITLE
Latest version (1.8.3) gives error System.OutOfMemoryException

### ISSUE THREAD

**Issue by SecondLayerOfHell** [microsoft/Microsoft-Win32-Content-Prep-Tool#65]
Hi,

I am trying to make a WinApp of a solidworks application, a large installation and it keeps giving me the error System.OutOfMemoryException. Something it didn't do on earlier version i used 1.7.3, now i am trying out 1.8.1 which seem to be working. 

What i can see in the taskmanager is that it eats up all memory and make most of windows unable to be used.

**Comment by sdahiya** [comment]
I

**Comment by sdahiya** [comment]
Hi Team - I am too facing same issue with multiple applications like Citrix Receiver, Argus.

**Comment by jeff-simeon** [comment]
The open source Simeon IntuneAppBuilder (https://github.com/simeoncloud/IntuneAppBuilder) does not suffer from this limitation. (Full disclosure, I work at Simeon).

**Comment by sdahiya** [comment]
Thanks @jeff-simeon. I will try Simeon. But I found the issue which was due to my ignorance of placing multiple files in folder being packaged. I was able to package all software so far.

**Comment by jeff-simeon** [comment]
Simeon uses a FileStream internally and does not load the full contents of any of the packaged files into memory, which allows it to work without the same memory limitations of the Microsoft tool.

**Comment by gvijaykumar20** [comment]
Hey everyone, 
This issue is now fixed with the latest release ([v1.8.4](https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/pull/70)).
