### ISSUE TITLE
The setup file you specified cannot be accessed

### ISSUE THREAD

**Issue by Andyhand** [microsoft/Microsoft-Win32-Content-Prep-Tool#69]
![image](https://user-images.githubusercontent.com/103491568/162914809-4e240990-b9bf-43fa-82ed-720e1fd5a0ec.png)

**Comment by ImJoakim** [comment]
The file you specify needs to be in the source folder you specified:

![image](https://user-images.githubusercontent.com/52826317/165189146-84455c62-2b22-4f84-aabb-4d77ed7055a9.png)
