### ISSUE TITLE
Regression "The setup file you specified can not be accessed"

### ISSUE THREAD

**Issue by bf** [microsoft/Microsoft-Win32-Content-Prep-Tool#72]
Hey guys, just wanted to let you know that I noticed there is a regression for the IntuneWinAppUtil.exe.

This one works (oldest commit in repo): https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/blob/bfc8b1c2979733e0b3e9fe7984ec6fd44acc0781/IntuneWinAppUtil.exe

This one throws error "The setup file you specified can not be accessed": https://github.com/microsoft/Microsoft-Win32-Content-Prep-Tool/blob/f83d16c68a0651b0eaf982d9562bde2593147af5/IntuneWinAppUtil.exe

Also the latest release throws the error for me.

My setup is an elevated powershell in Win7 working on a Virtualbox shared folder which is mounted as Z:\. Virtualbox host is linux, Virtualbox guest is Win7.

Might be that you deprecated Win7 support, but in all versions the command line dialog works. It is just that the file access throws an error.

**Comment by ameltzer-MSFT** [comment]
#69
