### ISSUE TITLE
Long file paths cause error when packaging apps

### ISSUE THREAD

**Issue by johndeshano** [microsoft/Microsoft-Win32-Content-Prep-Tool#73]
If the path of one of the files is longer than I believe 260 characters (MAX_PATH length) the prep tool will error out and fail.

A lot of the apps I package are saved in OneDrive, and ActivInspire in particular has some long paths, I had to move the data out to a shorter path to get it to package.

**Comment by ameltzer-MSFT** [comment]
#68
