### ISSUE TITLE
Did someone get "release it to GitHub" wrong?

### ISSUE THREAD

**Issue by rickmark** [microsoft/Microsoft-Win32-Content-Prep-Tool#75]
So -

There is ZERO value in using a Git repo for something that could be in the Microsoft download center.

Either release the software FOSS (sane) or move this to a non source-code hosting scheme (download.microsoft.com)...

It honestly feels like someone said "put it up on GitHub" and while ... technically you did... it's by no means useful this way

**Comment by jozefizso** [comment]
@stevgao When this tool will be open sourced? It does not make sense to commit binary to git.

**Comment by michaelmsonne** [comment]
@jozefizso as I had seen with this, I as tried to send an email to @stevgao ´s microsoft email at https://github.com/stevgao - but is does not exist anymore.

I had (and other to) open issues regarding the same bugs :(

**Comment by ameltzer-MSFT** [comment]
#28
