### ISSUE TITLE
System Component vs User Component

### ISSUE THREAD

**Issue by safehome-jdev** [microsoft/Microsoft-Win32-Content-Prep-Tool#76]
Using the tool does not allow an administrator to indicate if the input application is a system or user component. Currently, we're using 7zip to open the package and modify the Detection.xml file to state it is a system component install.

By default the tool creates a user component intune file.

Are there steps to allow/make the tool force a specific component type that is undocumented publicly?

**Comment by sikkepitje** [comment]
You should specify if the install behavior is 'system' or 'user' when
adding a win32 app to Intune ; . It makes no difference for the packaging
tool .

met vriendelijke groeten,
Paul Wiegmans 🐬


Op vr 3 jun. 2022 om 20:34 schreef safehome-jdev ***@***.***>:

**Comment by svdbusse** [comment]
The install context is based on what is set in the MSI. Poorly packaged apps may have this property set incorrectly. The work around is to not specify the MSI and instead pass an empty txt file. This allows you to set system or user as you see fit when you upload to intune. 

However, you do lose the convenience of auto populated install and uninstall commands as well as the MSI detection method.

I agree that an override parameter or prompt would be beneficial as part of the packaging tool.

**Comment by ameltzer-MSFT** [comment]
#63
