### ISSUE TITLE
Cannot Run IntuneWinAppUtil.exe

### ISSUE THREAD

**Issue by shkosugiMS** [microsoft/Microsoft-Win32-Content-Prep-Tool#8]
![image](https://user-images.githubusercontent.com/49278955/59837228-daaab780-9387-11e9-8946-901811cfd21a.png)

**Comment by bufferedreader** [comment]
Please click "Clone or Download" then click "Download ZIP" to download the "REAL" IntuneWinAppUtil.exe.
![image](https://user-images.githubusercontent.com/22878902/62873928-db8e1300-bd52-11e9-99ef-0f4256b7aeb5.png)

**Comment by nikyusof** [comment]
Thank you @bufferedreader for the response.
@shkosugiMS see the above response for the solution to your issue.

**Comment by RogerHeugen** [comment]
Thanks!
