### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by Hackmuss** [microsoft/Microsoft-Win32-Content-Prep-Tool#80]
Tried to use the tool to package an Office 365 language pack executable file. It seemed to get to 22% and then threw the following error:
ERROR System.IO.FileNotFoundException: Could not load file or assembly 'System.Io.Compression, Version=4.2.0.0, Culture=neutral, PublicKeyToken=xxxxxxxxxxxxxxxxxxxxxxxx' or one of its dependencies. The system cannot find the file specified.

**Comment by Hackmuss** [comment]
OK - just tried running it on a different machine and this time it worked so maybe my .NET is corrupt on the first machine. I'll repair and see if it fixes it.

**Comment by KieranThorpe** [comment]
did you resolve this in the end? Getting the same issue - the errors suggests making a change in the  registry which has made no difference

**Comment by Hackmuss** [comment]
I only experienced the issue one time. It's never done it again, so sorry - can't really offer any suggestions.

**Comment by KieranThorpe** [comment]
If its at all hjelpful i was trying to run this on a box hosted in Azure which fired this error - installing on my local machine had no issues - i'll see if i can do some further testing.

cheers for the reply
