### ISSUE TITLE
Get variables from system requesting the app

### ISSUE THREAD

**Issue by LickABrick** [microsoft/Microsoft-Win32-Content-Prep-Tool#82]
Hi, I couldn't find anything about this but it would be cool to get some variables passed from the management extension when someone requests the app.

For example, some apps need to be installed with Administrator permissions (which the user might not have) but after the installation is complete we might need to do something in the context of the user (i.e. activate a software license).

It would be nice if some variables are passed from the Intune Management extension which are usable in a Powershell script in te IntuneWin file. I.e. it would pass me the username of the user requesting the application, within the deployment script we can now place files in the users profile on the device or deploy a certain license which belongs to a specific user.

I know it is possible to get the currently logged on users from within Powershell, but this might not always be accurate if someone is using a shared device and other users are still signed in.

Let me know what you guys think.

**Comment by khaffner** [comment]
Look into PSAppDeployToolkit
