### ISSUE TITLE
Error when trying to create Intunewin package

### ISSUE THREAD

**Issue by kbstall** [microsoft/Microsoft-Win32-Content-Prep-Tool#84]
Greetings,

I am new to GitHub and Intune.  Ran into error today.
Running Windows 11 22H2.  Not sure if the 22H2 update did this, kind of seems like it.  Worked fine before update.  Character count for "true" path is 121.  Have also copied to folder/file to desktop, same error.  Any help or direction would be appreciated

Please specify the source folder: "C:\Users\My.Name\My Company\My OneDrive\Software\AutoPilot\Zoom\ZoomInstaller\ZoomInstaller.exe"
ERROR  The folder you specified can not be accessed.

**Comment by Gbischof-820** [comment]
Me and a fellow co-working are both running Windows 11 22H2, after the update, no output file is created when running the prep tool.

I can move everything over to a windows 10 22H2 pc and it works with out issue.

**Comment by proberg** [comment]
Hi, have the same issue with win11 22h2 22621.819
no output file is created when running the prep tool.
Also on win11 insider release 22623.1028 it will not create output file. 

Using an machine with win10 it works without problems.

**Comment by iwuvalpacas** [comment]
After some testing i found out that you can start intunewinapputil.exe with CMD or powershell and it will work as intended. As a workaround

**Comment by ddani05** [comment]
Was running into the same issue. Running the intunewinapputil.exe with CMD / Powershell worked. Thanks! @iwuvalpacas

**Comment by cynicalmax** [comment]
Thanks that worked for me too!
It should get updated for Win11 asap imo

**Comment by kbstall** [comment]
I have been successful in running utility as administrator.  Just right-click and select "Run as administrator".

**Comment by ThatDevDiaz** [comment]
Running as CMD did not work for me but can confirm running the tool as an admin (even though I was already logged into an Admin) worked.
