### ISSUE TITLE
[Bug] - Call from .Net/C# code fail when Windows Terminal is set to "Default terminal application = Windows Terminal" - works fine if set to "Default terminal application = Windows Console Host" - Windows 11 22621.963, Windows Terminal 1.15.3466.0

### ISSUE THREAD

**Issue by michaelmsonne** [microsoft/Microsoft-Win32-Content-Prep-Tool#85]
This is a bug, as I had tested my tool on a Windows Server 2016 where it runs fine.

When I call the tool from .Net/C# code it fail when Windows Terminal is set to "Default terminal application = Windows Terminal" - and it works fine if set to "Default terminal application = Windows Console Host".

Im running:
Windows 11 22621.963
Windows Terminal 1.15.3466.0

Code 1:
var tool = appPath + @"\IntuneWinAppUtil.exe";
string cmd = string.Format("/C {0} -c {1} -s {2} -o {3} -q", tool, dbfPath, dbfFile, textBoxOutput.Text);
System.Diagnostics.Process.Start("CMD.exe", cmd);

Code 2:
var appPath = Application.StartupPath;
var dbfFile = Path.GetFileName(textBoxSource.Text);
var dbfPath = Path.GetDirectoryName(textBoxSource.Text);
var startInfo = new ProcessStartInfo();
startInfo.CreateNoWindow = false;
startInfo.UseShellExecute = false;
startInfo.FileName = appPath + @"\IntuneWinAppUtil.exe";
var c = (char)34;
startInfo.WindowStyle = ProcessWindowStyle.Hidden;
startInfo.Arguments = " -c " + c + dbfPath + c + " -s " + c + dbfFile + c + " -o " + c + textBoxOutput.Text + c + " -q";

What is happening - it fail when run, and no .intunewin file it comming in the output folder!

When running the SAME code if set to "Windows Console Host" the .intunewin file it comming in the output folder fine!

Thanks, please help or fix!

![error](https://user-images.githubusercontent.com/49366751/212184279-a87c0f72-e70b-47d9-b8de-e3f7579341ea.png)

Workaround: Set Windows Terminal to use "Default terminal application" > Windows Console Host

**Comment by michaelmsonne** [comment]
Any updates @stevgao ? :)

**Comment by michaelmsonne** [comment]
Looks like there is not so much activity at this tool...

**Comment by ashek-simeon** [comment]
@michaelmsonne You could give this open source tool [http://github.com/simeoncloud/IntuneAppBuilder/](https://github.com/simeoncloud/IntuneAppBuilder/) from my team at Simeon Cloud a try as an alternative. We would greatly appreciate any feedback you have about it.

**Comment by michaelmsonne** [comment]
@ashek-simeon I can take a look
It looks like nothing is fixed here and the source code is not public too, so we can try to fix it by ourself.. :(

**Comment by ameltzer-MSFT** [comment]
#122
