### ISSUE TITLE
Prep Tool 100% Not Working

### ISSUE THREAD

**Issue by GNLaForgia-Bruner** [microsoft/Microsoft-Win32-Content-Prep-Tool#92]
Not sure what the issue is, but no matter what PC, what file or file type, the prep tool isn't working. It runs and closes without producing the intunewin file.

**Comment by GNLaForgia-Bruner** [comment]
Running on Windows 10 Enterprise. There isn't an output as it flies through the process then just exits.

**Comment by corbob** [comment]
And how are you launching it?
