### ISSUE TITLE
Can not create win32 app in windows 11

### ISSUE THREAD

**Issue by elliniomb** [microsoft/Microsoft-Win32-Content-Prep-Tool#95]
I can run the application, provide a directory, and run the application; however, when I try to create an app, the bar at the bottom drops to 75% and the application closes.

I test it with windows 10 and working but in my windows 11 doesn't, I'm using windows 11 ,22H@ enterprise

**Comment by CJPCNZ** [comment]
If you go to Settings > Privacy & security > For developers, what is listed as your Terminal?

For me, changing this from Windows Terminal to Windows Console Host fixed the issue.

**Comment by abe-tn** [comment]
I faced this issue. I resolved it by running Terminal/The app with admin privileges

**Comment by ameltzer-MSFT** [comment]
#122
