### ISSUE TITLE
.intunewin File Size is huge after using

### ISSUE THREAD

**Issue by carsonrossi** [microsoft/Microsoft-Win32-Content-Prep-Tool#96]
my exe file i used was originally 4.24 MB and it turned that into 15.8 GB after using the tool. i cant upload that into intune its too big what am i doing wrong? I've used this successfully in the past but only with msi files

**Comment by carsonrossi** [comment]
wow nevermind, it did this because i had other files in my downloads folder and it must have wrapped them all up into it that is interesting. So after i deleted all the excess files and ran it again it works. I wonder why it grabs every single thing from the downloads folder when i told it to only target the setupistation.exe here is the command i used C:\Users\rossi.carson\Downloads>IntuneWinAppUtil.exe -c C:\Users\rossi.carson\Downloads -s setupistation.exe -o D:\Intune

**Comment by jgudmundson-RETSD** [comment]
> 

-c is the source (it captures this entire directory)
-s is the installer.  It captures data from this file that intune uses to auto populate the win32 app.

**Comment by carsonrossi** [comment]
That makes sense thank you
