### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by Stensel8** [microsoft/Microsoft-Win32-Content-Prep-Tool#99]
The application crashes at about 60%. I'm using Windows 11 Pro

I can't see what's going wrong.

I'm trying to package Adobe Acrobat Reader 64 BIT with custom MST and INI files created using the Adobe Acrobat Customization Wizard.

**Comment by EMKody137** [comment]
Hi, I am not a Microsoft employee, but I just thought it might be useful for you to share what I have learned in trying to distribute Adobe products. I have found it infinitely easier to download the Adobe Creative Cloud app from the Microsoft store (these apps are easier to distribute than packaging the Win32 app). This works regardless of whether your end user is using a Creative Cloud license. An example of this is within our organization, everyone on our sales team uses Acrobat, but I distribute this way, so I don't have to manage the packages files. Once CC is installed you just have to open the CC app and click install on any of the Adobe products that you want added. The downside of this method is that it does add the step of needing to go into CC and install the individual apps, but I have found that this task can be done easily during our IT onboarding. Hope you can find a solution that works, cheers!
